<?php $APPLICATION->IncludeComponent(
    'bitrix:news.list', 'articles_on_main',
    [
        'DISPLAY_DATE'                    => 'Y',
        'DISPLAY_NAME'                    => 'Y',
        'DISPLAY_PICTURE'                 => 'Y',
        'DISPLAY_PREVIEW_TEXT'            => 'Y',
        'AJAX_MODE'                       => 'Y',
        'IBLOCK_TYPE'                     => 'articles',
        'IBLOCK_ID'                       => 5,
        'NEWS_COUNT'                      => 4,
        'SORT_BY1'                        => 'TIMESTAMP_X',
        'SORT_ORDER1'                     => 'DESC',
        'SORT_BY2'                        => 'SORT',
        'SORT_ORDER2'                     => 'ASC',
        'FIELD_CODE'                      => ['NAME', 'PREVIEW_PICTURE'],
        'PROPERTY_CODE'                   => ['AUTHOR'],
        'SET_TITLE'                       => 'N',
        'SET_BROWSER_TITLE'               => 'N',
        'SET_META_KEYWORDS'               => 'Y',
        'SET_META_DESCRIPTION'            => 'Y',
        'SET_LAST_MODIFIED'               => 'Y',
        'INCLUDE_IBLOCK_INTO_CHAIN'       => 'Y',
        'ADD_SECTIONS_CHAIN'              => 'Y',
        'HIDE_LINK_WHEN_NO_DETAIL'        => 'Y',
        'INCLUDE_SUBSECTIONS'             => 'Y',
        'CACHE_TYPE'                      => 'Y',
        'CACHE_TIME'                      => 360000,
        'CACHE_FILTER'                    => 'Y',
        'CACHE_GROUPS'                    => 'N',
        'DISPLAY_TOP_PAGER'               => 'N',
        'DISPLAY_BOTTOM_PAGER'            => 'Y',
        'PAGER_TITLE'                     => 'Новости',
        'PAGER_SHOW_ALWAYS'               => 'Y',
        'PAGER_DESC_NUMBERING'            => 'N',
        'PAGER_DESC_NUMBERING_CACHE_TIME' => '36000',
        'PAGER_SHOW_ALL'                  => 'N',
        'PAGER_BASE_LINK_ENABLE'          => 'Y',
        'SET_STATUS_404'                  => 'Y',
        'PAGER_PARAMS_NAME'               => 'arrPager',
        'AJAX_OPTION_JUMP'                => 'N',
        'AJAX_OPTION_STYLE'               => 'Y',
        'AJAX_OPTION_HISTORY'             => 'N',
    ]
); ?>