<?
require($_SERVER['DOCUMENT_ROOT'] . '/bitrix/header.php');
?>

<? $APPLICATION->IncludeComponent(
	'bitrix:catalog',
	'store_deep_catalog',
	[
		'IBLOCK_TYPE'                                  => 'katalog',
		'IBLOCK_ID'                                    => '8',
		'ACTION_VARIABLE'                              => 'action',
		'PRODUCT_ID_VARIABLE'                          => 'id',
		'SECTION_ID_VARIABLE'                          => 'SECTION_ID',
		'SEF_MODE'                                     => 'Y',
		'SEF_FOLDER'                                   => '/katalog/',
		'AJAX_MODE'                                    => 'N',
		'CACHE_TYPE'                                   => 'Y',
		'CACHE_TIME'                                   => '36000000',
		'CACHE_FILTER'                                 => 'N',
		'CACHE_GROUPS'                                 => 'Y',
		'DISPLAY_PANEL'                                => 'N',
		'SECTION_SHOW_PARENT_NAME'                     => 'N',
		'SET_TITLE'                                    => 'Y',
		'SET_STATUS_404'                               => 'Y',
		'USE_FILTER'                                   => 'N',
		'USE_COMPARE'                                  => 'N',
		'PRICE_CODE'                                   => [
			0 => 'База',
		],
		'USE_PRICE_COUNT'                              => 'Y',
		'SHOW_PRICE_COUNT'                             => '1',
		'PRICE_VAT_INCLUDE'                            => 'Y',
		'PRICE_VAT_SHOW_VALUE'                         => 'Y',
		'SHOW_TOP_ELEMENTS'                            => 'N',
		'PAGE_ELEMENT_COUNT'                           => '8',
		'LINE_ELEMENT_COUNT'                           => '1',
		'ELEMENT_SORT_FIELD'                           => 'sort',
		'ELEMENT_SORT_ORDER'                           => 'asc',
		'LIST_PROPERTY_CODE'                           => [
			0 => 'PRICECURRENCY',
			1 => '',
		],
		'INCLUDE_SUBSECTIONS'                          => 'Y',
		'DETAIL_PROPERTY_CODE'                         => [
			0 => 'SIZE',
			1 => 'S_SIZE',
			2 => 'ARTNUMBER',
			3 => 'MATERIAL',
			4 => 'MANUFACTURER',
			5 => '',
		],
		'DETAIL_SHOW_PICTURE'                          => 'Y',
		'LINK_ELEMENTS_URL'                            => 'link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#',
		'DISPLAY_TOP_PAGER'                            => 'N',
		'DISPLAY_BOTTOM_PAGER'                         => 'Y',
		'PAGER_TITLE'                                  => 'Продукция',
		'PAGER_SHOW_ALWAYS'                            => 'N',
		'PAGER_TEMPLATE'                               => 'arrows',
		'PAGER_DESC_NUMBERING'                         => 'N',
		'PAGER_DESC_NUMBERING_CACHE_TIME'              => '36000000',
		'PAGER_SHOW_ALL'                               => 'N',
		'COMPONENT_TEMPLATE'                           => 'store_deep_catalog',
		'HIDE_NOT_AVAILABLE'                           => 'N',
		'HIDE_NOT_AVAILABLE_OFFERS'                    => 'N',
		'USER_CONSENT'                                 => 'N',
		'USER_CONSENT_ID'                              => '0',
		'USER_CONSENT_IS_CHECKED'                      => 'Y',
		'USER_CONSENT_IS_LOADED'                       => 'N',
		'AJAX_OPTION_JUMP'                             => 'N',
		'AJAX_OPTION_STYLE'                            => 'Y',
		'AJAX_OPTION_HISTORY'                          => 'N',
		'USE_MAIN_ELEMENT_SECTION'                     => 'Y',
		'DETAIL_STRICT_SECTION_CHECK'                  => 'N',
		'SET_LAST_MODIFIED'                            => 'N',
		'ADD_SECTIONS_CHAIN'                           => 'Y',
		'ADD_ELEMENT_CHAIN'                            => 'N',
		'CONVERT_CURRENCY'                             => 'Y',
		'USE_PRODUCT_QUANTITY'                         => 'N',
		'PRODUCT_QUANTITY_VARIABLE'                    => 'quantity',
		'PRODUCT_PROPS_VARIABLE'                       => 'prop',
		'PARTIAL_PRODUCT_PROPERTIES'                   => 'N',
		'SECTION_COUNT_ELEMENTS'                       => 'Y',
		'SECTION_TOP_DEPTH'                            => '2',
		'ELEMENT_SORT_FIELD2'                          => 'id',
		'ELEMENT_SORT_ORDER2'                          => 'desc',
		'DETAIL_SET_CANONICAL_URL'                     => 'N',
		'DETAIL_CHECK_SECTION_ID_VARIABLE'             => 'N',
		'SHOW_DEACTIVATED'                             => 'N',
		'SHOW_SKU_DESCRIPTION'                         => 'N',
		'USE_STORE'                                    => 'N',
		'PAGER_BASE_LINK_ENABLE'                       => 'N',
		'SHOW_404'                                     => 'N',
		'COMPATIBLE_MODE'                              => 'Y',
		'USE_ELEMENT_COUNTER'                          => 'Y',
		'DISABLE_INIT_JS_IN_COMPONENT'                 => 'N',
		'DETAIL_SET_VIEWED_IN_COMPONENT'               => 'N',
		'CURRENCY_ID'                                  => 'RUB',
		'SEF_URL_TEMPLATES'                            => [
			'sections'     => '',
			'section'      => '#SECTION_CODE#/',
			'element'      => '#SECTION_CODE#/#ELEMENT_CODE#/',
			'compare'      => '',
			'smart_filter' => '#SECTION_ID#/filter/#SMART_FILTER_PATH#/apply/',
		],
	],
	false
); ?>

<? require($_SERVER['DOCUMENT_ROOT'] . '/bitrix/footer.php'); ?>